mocker:
  enabled: true
  replicaCount: 1
  image:
    repository: qaas-mocker-example
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    httpPort: 8443
    grpcPort: 50051
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  env: []

keydb:
  enabled: true
  image:
    repository: eqalpha/keydb
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
  resources: {}

redisInsight:
  enabled: true
  image:
    repository: redis/redisinsight
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5540
  resources: {}
