{{- if .Values.keydb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qaas-mocker-example.fullname" . }}-keydb
  labels:
    {{- include "qaas-mocker-example.labels" . | nindent 4 }}
    app.kubernetes.io/component: keydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: keydb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: keydb
    spec:
      containers:
        - name: keydb
          image: "{{ .Values.keydb.image.repository }}:{{ .Values.keydb.image.tag }}"
          imagePullPolicy: {{ .Values.keydb.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ .Values.keydb.service.port }}
          {{- with .Values.keydb.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
