{{- if .Values.redisInsight.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qaas-mocker-example.fullname" . }}-redisinsight
  labels:
    {{- include "qaas-mocker-example.labels" . | nindent 4 }}
    app.kubernetes.io/component: redisinsight
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: redisinsight
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: redisinsight
    spec:
      containers:
        - name: redisinsight
          image: "{{ .Values.redisInsight.image.repository }}:{{ .Values.redisInsight.image.tag }}"
          imagePullPolicy: {{ .Values.redisInsight.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.redisInsight.service.port }}
          {{- with .Values.redisInsight.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
