{{- if .Values.redisInsight.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "qaas-mocker-example.fullname" . }}-redisinsight
  labels:
    {{- include "qaas-mocker-example.labels" . | nindent 4 }}
    app.kubernetes.io/component: redisinsight
spec:
  type: {{ .Values.redisInsight.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redisinsight
  ports:
    - name: http
      port: {{ .Values.redisInsight.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
